package gadget.theme.mcu.scheme

open class LightScheme : Scheme {

    constructor(source: Int) : super(source)

    constructor(scheme: Scheme) : super(scheme)

    override val primary: Int = primaryTone(40)
    override val onPrimary: Int = primaryTone(100)
    override val primaryContainer: Int = primaryTone(90)
    override val onPrimaryContainer: Int = primaryTone(10)
    override val secondary: Int = secondaryTone(40)
    override val onSecondary: Int = secondaryTone(100)
    override val secondaryContainer: Int = secondaryTone(90)
    override val onSecondaryContainer: Int = secondaryTone(10)
    override val tertiary: Int = tertiaryTone(40)
    override val onTertiary: Int = tertiaryTone(100)
    override val tertiaryContainer: Int = tertiaryTone(90)
    override val onTertiaryContainer: Int = tertiaryTone(10)
    override val error: Int = errorTone(40)
    override val onError: Int = errorTone(100)
    override val errorContainer: Int = errorTone(90)
    override val onErrorContainer: Int = errorTone(10)
    override val background: Int = neutralTone(99)
    override val onBackground: Int = neutralTone(10)
    override val surface: Int = neutralTone(99)
    override val onSurface: Int = neutralTone(10)
    override val surfaceVariant: Int = variantTone(90)
    override val onSurfaceVariant: Int = variantTone(30)
    override val outline: Int = variantTone(50)
    override val outlineVariant: Int = variantTone(80)
    override val shadow: Int = neutralTone(0)
    override val scrim: Int = neutralTone(0)
    override val inversePrimary: Int = primaryTone(80)
    override val inverseSecondary: Int = secondaryTone(80)
    override val inverseTertiary: Int = tertiaryTone(80)
    override val inverseSurface: Int = neutralTone(20)
    override val inverseOnSurface: Int = neutralTone(95)
}