package gadget.theme.mcu.scheme

open class NightScheme : Scheme {

    constructor(source: Int) : super(source)

    constructor(scheme: Scheme) : super(scheme)

    override val primary: Int = primaryTone(80)
    override val onPrimary: Int = primaryTone(20)
    override val primaryContainer: Int = primaryTone(30)
    override val onPrimaryContainer: Int = primaryTone(90)
    override val secondary: Int = secondaryTone(80)
    override val onSecondary: Int = secondaryTone(20)
    override val secondaryContainer: Int = secondaryTone(30)
    override val onSecondaryContainer: Int = secondaryTone(90)
    override val tertiary: Int = tertiaryTone(80)
    override val onTertiary: Int = tertiaryTone(20)
    override val tertiaryContainer: Int = tertiaryTone(30)
    override val onTertiaryContainer: Int = tertiaryTone(90)
    override val error: Int = errorTone(80)
    override val onError: Int = errorTone(20)
    override val errorContainer: Int = errorTone(30)
    override val onErrorContainer: Int = errorTone(80)
    override val background: Int = neutralTone(10)
    override val onBackground: Int = neutralTone(90)
    override val surface: Int = neutralTone(10)
    override val onSurface: Int = neutralTone(90)
    override val surfaceVariant: Int = variantTone(30)
    override val onSurfaceVariant: Int = variantTone(80)
    override val outline: Int = variantTone(60)
    override val outlineVariant: Int = variantTone(30)
    override val shadow: Int = neutralTone(0)
    override val scrim: Int = neutralTone(0)
    override val inversePrimary: Int = primaryTone(40)
    override val inverseSecondary: Int = secondaryTone(40)
    override val inverseTertiary: Int = tertiaryTone(40)
    override val inverseSurface: Int = neutralTone(90)
    override val inverseOnSurface: Int = neutralTone(20)
}